name: CI Documentation

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build documentation
        run: gradle javadoc
      - name: Publish Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.FLOW_TOKEN }}
          publish_dir: ./build/docs/javadoc
